### PR TITLE
Fix deal button

### LINKED ISSUE #40: Remove and Deal Problems
Cannot remove cards from the board or deal new cards.

### PR DESCRIPTION
**Pull request by bmikkelsen22**
Fixes #40

### CODE REVIEW

File: src/main/java/models/Deck.java [hunk 1]
```diff
@@ -2,13 +2,12 @@
 
 import java.util.ArrayList;
 
-public abstract class Deck {
+public class Deck {
```
Comment (NathanTan) [inline src/main/java/models/Deck.java]: The golden change! I like how clean the changes are in this commit to make our code work.
